services:
  gateway:
    build: ./gateway
    ports: ["8000:8000"]
  notifications:
    build: ./notifications
  reports:
    build: ./reports
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
